#!/bin/bash
# Author: Paulo Jerônimo <paulojeronimo@gmail.com>
#
# Script que gera uma apresentação com o asciidoc e dzslides.
# Utiliza uma versão customizada do dzslides (configurado em build.conf.sample)
# Executável no OSX. Para outros ambientes, adapte-o!
set +x

BASEDIR=`cd "$(dirname "$0")"; pwd`

for conf in build.conf build.conf.sample
do
  conf="$BASEDIR"/$conf
  if [ -f "$conf" ]
  then
    source "$conf" && break || exit 1
  fi
done
[ "$TARGET" ] || { echo "TARGET não configurado!"; exit; }

check_builder() {
  [ -f builder/.git ] || git submodule update --init builder
}

build() {
  check_builder
  builder/dzslides/build "$@"
}

server() {
  check_builder
  builder/dzslides/build server "$@"
}

clean() {
  rm -rf "$TARGET"
  rm -f images/presentation-qrcode.png
}

create_gh_pages_branch() {
  git checkout --orphan gh-pages
  rm -rf *
  git rm -rf .
  echo 'Página inicial' > index.html
  git add .
  git commit -m 'Commit inicial'
  git checkout master
  git push -u origin gh-pages
  git submodule add -b gh-pages `git config --get remote.origin.url` "$PUBLISHED"
  git add .
  git commit -m 'Adicionada a branch gh-pages'
  git push
}

publish_on_gh_pages() {
  publish_with_rsync

  [ -f "$PUBLISHED/.git" ] || git submodule update --init "$PUBLISHED"

  local msg="Publicação em `date +"%d/%m/%Y às %H:%M:%S"`"
  cd "$PUBLISHED"
  git add .
  git commit -m "$msg"
  git push origin HEAD:gh-pages
  cd ..
  git add "`basename "$PUBLISHED"`"
  git commit -m "$msg"
  git push
}

publish_with_rsync() {
  [ "$PUBLISHED" ] || { echo "PUBLISHED não configurado!"; return; }
  [ -d "$PUBLISHED" ] || mkdir -p "$PUBLISHED"
  [ -d "$TARGET" ] || { echo "O diretório \"$TARGET\" não existe!"; return; }
  rsync -av --update --delete --exclude '.git' "$TARGET"/ "$PUBLISHED"/
}

cd "$BASEDIR"
op=${1:-build}
shift
type "$op" &> /dev/null && $op "$@"
