#!/bin/bash
# Author: Paulo Jerônimo <paulojeronimo@gmail.com>
#
# Script que gera uma apresentação com o asciidoc e dzslides.
# Utiliza uma versão customizada do dzslides (configurado em build.conf.sample)
# Executável no OSX. Para outros ambientes, adapte-o!
set +x

BASEDIR=`cd "$(dirname "$0")"; pwd`

for conf in build.conf build.conf.sample
do
  conf="$BASEDIR"/$conf
  if [ -f "$conf" ]
  then
    source "$conf" && break || exit 1
  fi
done
[ "$DZSLIDES" ] || { echo "DZSLIDES não configurado!"; exit; }
[ "$TARGET" ] || { echo "TARGET não configurado!"; exit; }

install_asciidoc() {
  case $OSTYPE in
    darwin*) brew install asciidoc;;
    *) echo 'Por favor, instale o asciidoc!'; exit;;
  esac
}

install_qrencode() {
  case $OSTYPE in
    darwin*) brew install qrencode;;
    *) echo 'Por favor, instale o qrencode!'; exit;;
  esac
}

prepare() {
  which asciidoc > /dev/null || install_asciidoc
  which qrencode > /dev/null || install_qrencode
  pushd . &> /dev/null
  mkdir -p ~/.asciidoc && cd $_
  local f=qrcode-filter-1.0.zip
  if ! [ -f $f ]
  then
      wget -c http://asciidoc-qrencode-filter.googlecode.com/files/$f
      asciidoc --filter install $f
  fi
  mkdir -p ~/.asciidoc/backends && cd $_
  if ! [ -d dzslides ]
  then
      git clone git://github.com/mojavelinux/asciidoc-dzslides-backend.git dzslides
      cd dzslides
      git clone $DZSLIDES
  fi
  popd &> /dev/null
}

build() {
  prepare
  
  local not_linkcss
  mkdir -p "$TARGET"
  if [ "$1" == "--embbeded" ]
  then
    embedded="-a data-uri -a linkcss!"
  else
    rsync -a --update --delete ~/.asciidoc/backends/dzslides/dzslides "$TARGET"/
  fi
  asciidoc $embedded index.asciidoc && \
  mv index.html "$TARGET"/
  rsync -a --update --delete images "$TARGET"/
}

clean() {
  rm -rf "$TARGET"
  rm -f images/presentation-qrcode.png
}

publish_on_github() {
  publish_with_rsync

  local msg="Publicação em `date +"%d/%m/%Y às %H:%M:%S"`"
  cd "$PUBLISH"
  git commit -am "$msg"
  git push origin HEAD:gh-pages
  cd ..
  git add "`basename "$PUBLISH"`"
  git commit -m "$msg"
  git push
}

publish_with_rsync() {
  build

  [ "$PUBLISH" ] || { echo "PUBLISH não configurado!"; return; }
  [ -d "$PUBLISH" ] || mkdir -p "$PUBLISH"
  rsync -av --update --delete --exclude '.git' "$TARGET"/ "$PUBLISH"/
}

cd "$BASEDIR"
op=${1:-build}
shift
type "$op" &> /dev/null && $op "$@"
