#!/bin/bash

git checkout --orphan gh-pages
rm -rf *
git rm -rf .
echo 'Página inicial' > index.html
git add .
git commit -m 'Commit inicial'
git checkout master
git push -u origin gh-pages
git submodule add -b gh-pages `git config --get remote.origin.url` published
git add .
git commit -m 'Adicionada a branch gh-pages'
git push
